#!/bin/bash
# verify-release-manifest.test.sh — L1 spec for verify-release-manifest.sh
# (claude-workflow-plugin-h2zz waiver ruling, round 4).
#
# WHAT THIS PROTECTS. verify-release-manifest.sh carries the claim that used
# to live in workflow-manifest.test.sh's Section 6 before it was removed:
# "the frozen table named by .claude-plugin/plugin.json reproduces
# byte-for-byte from the tree of the tag it names, under the current
# generator." Section 6 could not stay in L1 because that claim cannot hold
# on a pre-release ref (see run-tests.sh's PRE-RELEASE-REF EXEMPTION:
# REMOVED tombstone for the six-finding account of why every attempt to
# exempt L1 from that fact narrowly enough failed). This spec is what stays
# offline and safe to run on every `make test`: it drives the RELOCATED
# script against CONSTRUCTED local git repos with their OWN local tags,
# never this project's own release tag and never a network call of any
# kind — the same technique Section 6b/6c used for the predicate/attestation
# script before they were removed alongside Section 6.
#
# WHY THIS IS OFFLINE AND SAFE, UNLIKE THE REMOVED SECTION 6. Section 6's
# defect was never "uses git tags" -- it was "asserts something about THIS
# repo's CURRENT, possibly-unpushed release tag, inside the tier that runs
# on every commit". A fixture with its own local-only tag, built and torn
# down inside $WORK, has no such dependency: it exists and is reachable the
# instant `git tag` runs, with no push, no remote, and no network stack
# involved at any point below.
#
# ASSERTION ANCHORING: every check is anchored to TEXT (an exit code, a
# diagnostic substring) and never to a line number, matching this
# codebase's LESSONS.md (2026-06-13) discipline.
set -u

PASS=0
FAIL=0
FAILED_TESTS=()

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "$0")/../../.." && pwd)}"
SCRIPT="$PROJECT_DIR/.claude/scripts/verify-release-manifest.sh"
WM_SCRIPT="$PROJECT_DIR/.claude/scripts/workflow-manifest.sh"

WORK=$(mktemp -d -t verify-release-manifest-test.XXXXXX)
# Invoked indirectly, by the EXIT trap immediately below.
# shellcheck disable=SC2329
cleanup() { rm -rf "$WORK" 2>/dev/null || true; }
trap cleanup EXIT

assert_eq() {
    local name="$1" expected="$2" actual="$3"
    if [ "$expected" = "$actual" ]; then
        PASS=$((PASS + 1))
        printf '  PASS: %s\n' "$name"
    else
        FAIL=$((FAIL + 1))
        FAILED_TESTS+=("$name")
        printf '  FAIL: %s\n    expected: %s\n    actual:   %s\n' \
            "$name" "$expected" "$actual"
    fi
}

assert_contains() {
    local name="$1" needle="$2" haystack="$3"
    case "$haystack" in
        *"$needle"*)
            PASS=$((PASS + 1))
            printf '  PASS: %s\n' "$name"
            ;;
        *)
            FAIL=$((FAIL + 1))
            FAILED_TESTS+=("$name")
            printf '  FAIL: %s\n    expected to contain: %s\n    actual:   %s\n' \
                "$name" "$needle" "$haystack"
            ;;
    esac
}

echo "=== Section 0: the script under test ==="
assert_eq "verify-release-manifest.sh exists at .claude/scripts/verify-release-manifest.sh" \
    "yes" "$([ -f "$SCRIPT" ] && echo yes || echo no)"
if [ ! -f "$SCRIPT" ]; then
    printf '\nFAILED: %d (script missing; remaining sections cannot run)\n' "$FAIL"
    exit 1
fi
assert_eq "verify-release-manifest.sh parses under bash -n" "0" \
    "$(bash -n "$SCRIPT" 2>/dev/null && echo 0 || echo 1)"

# mk_release_repo <root> <version> — a real, throwaway git repo carrying a
# plugin.json at <version>, a REAL LOCAL tag "v<version>" (never pushed
# anywhere; never this project's own tag), and a frozen table generated by
# THIS repo's own real, shipped workflow-manifest.sh against that exact
# tree — the same generator the script under test will use, so a match is a
# match on the real property, not a stand-in for it.
mk_release_repo() {
    local root="$1" version="$2"
    mkdir -p "$root/.claude-plugin" "$root/.claude/scripts"
    ( cd "$root" && git init -q && git config user.email t@t.com && git config user.name t )
    printf '{"version":"%s"}\n' "$version" > "$root/.claude-plugin/plugin.json"
    printf 'echo hello\n' > "$root/.claude/scripts/thing.sh"
    ( cd "$root" && git add -A && git commit -qm initial >/dev/null )
    mkdir -p "$root/manifests"
    bash "$WM_SCRIPT" generate "$root" > "$root/manifests/v$version.sha256" 2>/dev/null
    ( cd "$root" && git add -A && git commit -qm "freeze table" >/dev/null && git tag "v$version" )
}

# ---------------------------------------------------------------------------
echo ""
echo "=== Section 1: HAPPY PATH — a real local tag, table matches its tree ==="
R1="$WORK/repo-match"
mk_release_repo "$R1" "1.0.0"
OUT1=$(CLAUDE_PROJECT_DIR="$R1" bash "$SCRIPT" v1.0.0 2>&1)
RC1=$?
assert_eq "1.1 EXECUTION: a matching table against its own real local tag exits 0" "0" "$RC1"
assert_contains "1.2 ...and says OK, naming the tag" "OK -- manifests/v1.0.0.sha256 reproduces byte-for-byte from v1.0.0" "$OUT1"

# ---------------------------------------------------------------------------
echo ""
echo "=== Section 2: SPECIFIC MISBEHAVIOUR CLOSED — a ONE-BYTE corrupted table is caught ==="
# Same technique as workflow-manifest.test.sh's own META 4: mutate exactly
# one hash byte in a COPY, in a table that still passes plain format
# checking (valid 64-lowercase-hex), so this leg proves byte-for-byte
# comparison specifically, not merely "the file changed size".
R2="$WORK/repo-mismatch"
mk_release_repo "$R2" "2.0.0"
TABLE2="$R2/manifests/v2.0.0.sha256"
assert_eq "2.1 precondition: the frozen table has at least one row to corrupt" \
    "yes" "$([ -s "$TABLE2" ] && echo yes || echo no)"
awk -F'\t' -v OFS='\t' '
    NR == 1 {
        last = substr($3, 64, 1)
        $3 = substr($3, 1, 63) ((last == "0") ? "1" : "0")
    }
    { print }
' "$TABLE2" > "$TABLE2.mut"
mv "$TABLE2.mut" "$TABLE2"
( cd "$R2" && git add -A && git commit -qm "corrupt one hash byte, working tree only, tag left pointing at the original" >/dev/null )
OUT2=$(CLAUDE_PROJECT_DIR="$R2" bash "$SCRIPT" v2.0.0 2>&1)
RC2=$?
assert_eq "2.2 SPECIFIC MISBEHAVIOUR CLOSED: a one-byte-corrupted table against its own tag's tree exits 1" "1" "$RC2"
assert_contains "2.3 ...naming the mismatch explicitly" "is NOT byte-identical to the regenerated tag manifest" "$OUT2"
assert_contains "2.4 ...with a diagnostic showing the differing row" "diagnostic: first differing rows" "$OUT2"

# --- 2.5 RESTORE CONTROL: the SAME repo, tag re-pointed at the commit that
# actually carries the corrupted table, is a case verify-release-manifest.sh
# has no way to distinguish from "the generator changed" -- not exercised
# here (out of scope: this leg is about detecting mismatch, not diagnosing
# which side moved) -- instead, prove the detector is not just permanently
# red by running the ORIGINAL match fixture (Section 1) once more.
OUT2R=$(CLAUDE_PROJECT_DIR="$R1" bash "$SCRIPT" v1.0.0 2>&1)
RC2R=$?
assert_eq "2.5 RESTORE CONTROL: the untouched Section 1 fixture still exits 0 (the detector is not stuck red)" \
    "0" "$RC2R"
assert_contains "2.6 ...and still reports OK, not a stale FAIL message left over from Section 2" \
    "OK -- manifests/v1.0.0.sha256" "$OUT2R"

# ---------------------------------------------------------------------------
echo ""
echo "=== Section 2b: THE TAG SHIPS NO TABLE AT ALL (R5-F1, HIGH) ==="
# claude-workflow-plugin-h2zz round 5, R5-F1 (independent review, dual-family).
# CLAIM under test: the gate proves the frozen table reproduces from its tag
# AND is actually shipped by that tag. Before this round, (v) below (the
# byte-for-byte regeneration check exercised in Section 2 above) was the
# ONLY thing standing between "OK" and a tag that ships no frozen table --
# and (v) compares the regeneration against the WORKING-TREE copy of the
# table, never the tag's own committed copy, so a table added to the
# working tree AFTER the tag was cut, never committed into the tag at all,
# satisfied it trivially.
#
# THIS IS THE MANDATORY NEGATIVE CONTROL FOR R5-F1: this exact fixture,
# run against the PRE-FIX script, printed
#   "verify-release-manifest.sh: OK -- manifests/v2.5.0.sha256 reproduces byte-for-byte from v2.5.0 (2 rows)"
# and exited 0 (hand-verified before this leg existed, both directly against
# a throwaway fixture and by temporarily reverting the shipped script to its
# pre-fix text and running this exact leg against it -- see the task's
# completion report for both transcripts).
R2B="$WORK/repo-no-table-at-tag"
mkdir -p "$R2B/.claude-plugin" "$R2B/.claude/scripts"
( cd "$R2B" && git init -q && git config user.email t@t.com && git config user.name t )
printf '{"version":"2.5.0"}\n' > "$R2B/.claude-plugin/plugin.json"
printf 'echo hello\n' > "$R2B/.claude/scripts/thing.sh"
( cd "$R2B" && git add -A && git commit -qm initial >/dev/null && git tag v2.5.0 )
# The table is generated into the WORKING TREE only, strictly AFTER the tag
# above -- never committed, never part of v2.5.0's own tree. This is the
# defect scenario itself, not a corruption of an otherwise-frozen table.
mkdir -p "$R2B/manifests"
bash "$WM_SCRIPT" generate "$R2B" > "$R2B/manifests/v2.5.0.sha256"
OUT2B=$(CLAUDE_PROJECT_DIR="$R2B" bash "$SCRIPT" v2.5.0 2>&1)
RC2B=$?
assert_eq "2b.1 SPECIFIC MISBEHAVIOUR CLOSED: a tag that ships NO table at all exits 1 (genuine mismatch, not a silent 0)" \
    "1" "$RC2B"
assert_contains "2b.2 ...and names the actual problem (the tag does not carry the table)" \
    "does not carry manifests/v2.5.0.sha256 at all" "$OUT2B"
# `case` as a plain statement, NOT inline inside `$(...)`: bash 3.2's
# command-substitution parser mis-reads a case pattern's `)` as the closing
# paren of `$( ... )`, so `$(case ... esac)` is a syntax error at runtime on
# macOS even though it parses clean under `bash -n` and shellcheck (observed
# here, not theoretical -- see the same avoidance in workflow-doctor.test.sh's
# has_word and mcp-deps.test.sh's starts_with).
case "$OUT2B" in
    *"OK --"*) OUT2B_SAYS_OK=yes ;;
    *)         OUT2B_SAYS_OK=no ;;
esac
assert_eq "2b.3 ...and never prints the OK line for a tag that ships no frozen table" \
    "no" "$OUT2B_SAYS_OK"

# --- 2b.4 RESTORE CONTROL: the detector is not stuck red after this fixture.
OUT2BR=$(CLAUDE_PROJECT_DIR="$R1" bash "$SCRIPT" v1.0.0 2>&1)
RC2BR=$?
assert_eq "2b.4 RESTORE CONTROL: the untouched Section 1 fixture still exits 0 after Section 2b" \
    "0" "$RC2BR"
assert_contains "2b.5 ...and still reports OK, not a stale FAIL message left over from Section 2b" \
    "OK -- manifests/v1.0.0.sha256" "$OUT2BR"

# ---------------------------------------------------------------------------
echo ""
echo "=== Section 3: PRECONDITION FAILURES fail CLOSED and LOUD (exit 2), never a silent skip ==="
# claude-workflow-plugin-h2zz waiver ruling: unlike the removed Section 6,
# this script is invoked ONLY from contexts where the check is expected to
# be meaningful (a release checklist; a tag-triggered CI job) -- an
# unreachable tag or missing table here is a real problem worth a loud,
# nonzero exit, not the ordinary/non-exempt "note: SKIPPED" shape L1 specs
# use for a legitimately-absent prerequisite.
R3="$WORK/repo-precondition"
mk_release_repo "$R3" "3.0.0"

# 3.1/3.2 exercise the TAG-UNREACHABLE branch specifically (R5-F2, MEDIUM,
# claude-workflow-plugin-h2zz round 5). The table-missing check runs FIRST
# in the script (before the reachability check ever gets a chance to run),
# so a leg that omits BOTH the table and the tag never actually reaches the
# reachability branch -- it always exits at the table-missing check instead,
# leaving reachability untested even though its own assertion exits 2 too.
# A table is created here for a tag name that is never git-tagged, so the
# table-missing check passes and the reachability check is the one that
# actually fires. Leg 3.3/3.4 below is the DISTINCT, non-redundant coverage
# for the table-missing branch: a real, reachable tag with no table for it.
cp "$R3/manifests/v3.0.0.sha256" "$R3/manifests/v9.9.9-does-not-exist-anywhere.sha256"
OUT3A=$(CLAUDE_PROJECT_DIR="$R3" bash "$SCRIPT" v9.9.9-does-not-exist-anywhere 2>&1)
RC3A=$?
assert_eq "3.1 PRECONDITION: a table exists for the name but the tag itself is unreachable exits 2" "2" "$RC3A"
assert_contains "3.2 ...and names the reachability reason specifically, not the missing-table branch 3.3/3.4 covers" \
    "is not reachable here" "$OUT3A"

( cd "$R3" && git tag v3.9.9 )
OUT3B=$(CLAUDE_PROJECT_DIR="$R3" bash "$SCRIPT" v3.9.9 2>&1)
RC3B=$?
assert_eq "3.3 PRECONDITION: a real, reachable tag with NO frozen table for it exits 2" "2" "$RC3B"
assert_contains "3.4 ...and names which table is missing" "manifests/v3.9.9.sha256 has not been frozen yet" "$OUT3B"

OUT3C=$(CLAUDE_PROJECT_DIR="$R3" bash "$SCRIPT" 2>&1)
RC3C=$?
assert_eq "3.5 PRECONDITION: no argument, derived from THIS fixture's own plugin.json (v3.0.0, which DOES exist and match) exits 0" \
    "0" "$RC3C"
assert_contains "3.6 ...proving the derivation path (not just the explicit-argument path) actually runs" \
    "OK -- manifests/v3.0.0.sha256 reproduces byte-for-byte from v3.0.0" "$OUT3C"

# ---------------------------------------------------------------------------
# SECTION 4: REMOVED (R5-F3, LOW, claude-workflow-plugin-h2zz round 5).
# It used to hold one leg, "4.1 NON-VACUITY", which grepped the script's
# SOURCE for the literal substring CLAUDE_PROJECT_DIR -- satisfiable by a
# comment or a dead assignment, proving nothing about runtime behaviour.
#
# NON-VACUITY for the whole spec above is BEHAVIOURAL instead, and was
# already there before this section was deleted: leg 1.1 exits 0 against
# v1.0.0 and leg 3.5 exits 0 against v3.0.0, tags that exist ONLY inside
# their own constructed $WORK fixtures. This project's own real tags are
# v3.5.0, v4.0.0, v4.1.0 and v5.0.0 (verify with `git tag --list` against
# the real repo) -- neither v1.0.0 nor v3.0.0 among them -- so neither leg
# could have passed had CLAUDE_PROJECT_DIR been ignored and the script
# fallen back to the real repository: `git rev-parse --verify` would have
# found no such tag there and both legs would have exited 2, not 0. Kept as
# a tombstone rather than silently closing the numbering gap, matching this
# file's own citation of workflow-manifest.test.sh's Section 6 tombstone:
# a reader who remembers "Section 4" should find out why it is gone rather
# than wonder whether they misremembered. Section 5 below is the first real
# use of the numbering after this tombstone.
# ---------------------------------------------------------------------------
echo ""
echo "=== Section 5: THE MAKEFILE WIRING (claude-workflow-plugin-h2zz round 6,"
echo "R6-F2, MEDIUM) -- RELEASE_TAG reaches this script as environment data,"
echo "expanded only as a quoted shell reference by the recipe's OWN shell,"
echo "and is never spliced into recipe source by make itself ==="
# The SAME injection class R5-F5 fixed in .github/workflows/release-verify.
# yml (env: + a quoted "$RELEASE_TAG" reference) was left open in the
# Makefile's own verify-release recipe -- `$(RELEASE_TAG)` spliced straight
# into recipe source, unquoted. `git check-ref-format` has no objection to a
# tag containing shell metacharacters -- `v1;id` and `v$(id)` are both LEGAL
# refs (`git check-ref-format` exits 0 for each, verified directly), so this
# was reachable via an entirely ordinary-looking tag, not just a
# deliberately hostile override. (The fixture values exercised below --
# "INJECTED", marker-touching commands -- are chosen for observability, not
# for ref-legality: the injection is a Makefile/shell splicing property and
# never depends on git validating the value at all.)
MAKEFILE="$PROJECT_DIR/Makefile"
assert_eq "5.0 precondition: the real Makefile exists" \
    "yes" "$([ -f "$MAKEFILE" ] && echo yes || echo no)"

# The exact shipped recipe line (verified byte-for-byte via `od -c` against
# the real file) and the PRE-FIX line it replaced. Hardcoded, not derived --
# this file's own ASSERTION ANCHORING convention (header above) anchors to
# exact text; a test that derived "the fixed line" FROM the file under test
# could not also prove that file reads what this comment claims it reads.
FIXED_LINE=$'\t@bash .claude/scripts/verify-release-manifest.sh $${RELEASE_TAG:+"$$RELEASE_TAG"}'
PREFIX_LINE=$'\t@bash .claude/scripts/verify-release-manifest.sh $(RELEASE_TAG)'
assert_eq "5.0b precondition: the shipped recipe line reads exactly what this section's mutation targets" \
    "yes" "$(grep -qF "$FIXED_LINE" "$MAKEFILE" && echo yes || echo no)"

# 5.1 NON-VACUITY -- mutate a COPY of the shipped Makefile back to the
# PRE-FIX splice and prove the substitution actually landed, via a hit
# counter that would read 0 (loudly, not silently) had the anchor text not
# matched, plus a whole-file diff confined to that one line -- same
# discipline as workflow-manifest.test.sh's awk mutants (found-check +
# byte-comparison), adapted to line-exact text since a Makefile recipe's
# leading TAB makes it hostile to a regex-based sed/awk substitution.
MUT_MAKEFILE="$WORK/Makefile.prefix-splice"
MUT_HITS=0
: > "$MUT_MAKEFILE"
while IFS= read -r _s5_line || [ -n "$_s5_line" ]; do
    if [ "$_s5_line" = "$FIXED_LINE" ]; then
        printf '%s\n' "$PREFIX_LINE" >> "$MUT_MAKEFILE"
        MUT_HITS=$((MUT_HITS + 1))
    else
        printf '%s\n' "$_s5_line" >> "$MUT_MAKEFILE"
    fi
done < "$MAKEFILE"
assert_eq "5.1 NON-VACUITY: the pre-fix mutant replaced the recipe's arg-passing exactly once" \
    "1" "$MUT_HITS"
assert_eq "5.1b ...and the mutant is otherwise byte-identical to the shipped Makefile (a one-line diff, not a reimplementation)" \
    "2" "$(diff "$MAKEFILE" "$MUT_MAKEFILE" 2>/dev/null | grep -c '^[<>]' | tr -d ' \n')"

# 5.2 SPECIFIC MISBEHAVIOUR, TEXTUAL -- `make -n` (dry run; the task's own
# reproduction technique) against the mutant. A metacharacter-bearing
# RELEASE_TAG splices straight into the printed recipe as a SECOND,
# unquoted shell command.
OUT52=$(make -C "$PROJECT_DIR" -n -f "$MUT_MAKEFILE" verify-release RELEASE_TAG='v1;printf INJECTED' 2>&1)
assert_contains "5.2 SPECIFIC MISBEHAVIOUR: the pre-fix mutant's dry-run shows the value spliced as a SECOND, unquoted command" \
    "verify-release-manifest.sh v1;printf INJECTED" "$OUT52"

# 5.2b SPECIFIC MISBEHAVIOUR, BEHAVIOURAL -- the same mutant, executed for
# REAL (no -n): a marker file the injected command would create, never
# created via any destructive action (touch/echo only), proves the splice
# is not just visible in dry-run text but genuinely runs. Also documents the
# FULL blast radius: the injected trailing `echo` becomes the LAST command
# on the compound line, so ITS exit code (0) is what make sees -- the real
# script's own exit 2 (precondition failure) is masked, and a release gate
# that should have stopped the release reports success instead.
MUT_MARKER="$WORK/r6f2-mutant.marker"
rm -f "$MUT_MARKER"
MUT_INJECT_TAG="v1;touch $MUT_MARKER;echo r6f2-mutant-echo-proof"
OUT52B=$(make -C "$PROJECT_DIR" -f "$MUT_MAKEFILE" verify-release RELEASE_TAG="$MUT_INJECT_TAG" 2>&1)
RC52B=$?
assert_eq "5.2c SPECIFIC MISBEHAVIOUR, BEHAVIOURAL: the pre-fix mutant genuinely executes the injected command (marker created)" \
    "yes" "$([ -f "$MUT_MARKER" ] && echo yes || echo no)"
assert_eq "5.2d ...and the injected trailing command MASKS the real check's own exit 2 (make sees exit 0 -- a release gate falsely reporting success)" \
    "0" "$RC52B"
assert_contains "5.2e ...and the injected echo's OWN output is captured too (the compound line genuinely ran as three commands, not one)" \
    "r6f2-mutant-echo-proof" "$OUT52B"

# 5.3 RESTORE CONTROL, TEXTUAL -- the SAME dry-run, same metacharacter
# value, same call shape, against the REAL shipped Makefile. If this also
# leaked the spliced form, 5.2 would be an artefact of `-n` itself rather
# than of the mutation.
OUT53=$(make -C "$PROJECT_DIR" -n verify-release RELEASE_TAG='v1;printf INJECTED' 2>&1)
assert_eq "5.3 RESTORE CONTROL: the shipped Makefile's dry-run does NOT leak the raw value" \
    "no" "$(printf '%s' "$OUT53" | grep -qF 'v1;printf INJECTED' && echo yes || echo no)"
# shellcheck disable=SC2016  # single-quoted on purpose: the needle is the
# LITERAL, unexpanded parameter-expansion text make itself prints under -n;
# double-quoting would expand $RELEASE_TAG in THIS script's own (unset)
# environment instead of matching make's literal output.
#
# claude-workflow-plugin-h2zz R8-F2: this assertion's name used to read
# "...(make itself never touches the value)" as a blanket claim. False --
# see Section 5.5 below, which is exactly the case where make DOES touch the
# value (expanding $(...)/${...} syntax inside it while building the
# recipe's environment) despite this dry-run text never changing. What THIS
# leg actually proves is narrower and still true: the RECIPE TEXT itself is
# never spliced with the raw value (the R6-F2 injection vector), which is
# the only thing `make -n` can show at all -- it prints the recipe as make
# would run it, before the shell (or make's own environment-export step)
# ever touches RELEASE_TAG's value.
assert_contains "5.3b ...it shows the quoted shell-side reference instead (the RECIPE TEXT is never spliced with the raw value -- see Section 5.5 for the separate, make-level expansion issue this dry-run cannot show)" \
    'verify-release-manifest.sh ${RELEASE_TAG:+"$RELEASE_TAG"}' "$OUT53"

# 5.3c RESTORE CONTROL, BEHAVIOURAL -- the SAME marker-file technique as
# 5.2b, against the REAL shipped Makefile: no marker, and the real script's
# own exit 2 propagates un-masked (proving 5.2d's masking is specific to
# the pre-fix splice, not a property of the script or of make's exit-code
# handling in general).
SHIP_MARKER="$WORK/r6f2-shipped.marker"
rm -f "$SHIP_MARKER"
SHIP_INJECT_TAG="v1;touch $SHIP_MARKER;echo v1"
OUT53C=$(make -C "$PROJECT_DIR" verify-release RELEASE_TAG="$SHIP_INJECT_TAG" 2>&1)
RC53C=$?
assert_eq "5.3c RESTORE CONTROL, BEHAVIOURAL: the shipped Makefile creates no marker (nothing injected actually runs)" \
    "no" "$([ -f "$SHIP_MARKER" ] && echo yes || echo no)"
assert_eq "5.3d ...and the real precondition failure propagates as exit 2, un-masked" \
    "2" "$RC53C"
assert_contains "5.3e ...the value reached the script as ONE literal string, visible whole in its own diagnostic" \
    "$SHIP_INJECT_TAG" "$OUT53C"

# 5.4 EXECUTION -- the shipped Makefile, for REAL (no -n, no mutant),
# driving the real script against Section 1's own fixture (R1): the
# ordinary, no-override path must still derive the tag from the fixture's
# OWN plugin.json and succeed, exactly as it would for an operator running
# `make verify-release` with no RELEASE_TAG override.
OUT54=$(CLAUDE_PROJECT_DIR="$R1" make -C "$PROJECT_DIR" verify-release 2>&1)
RC54=$?
assert_eq "5.4 EXECUTION: the real recipe, no override, against a fixture repo exits 0" "0" "$RC54"
assert_contains "5.4b ...and reports OK for the fixture's own tag (the no-argument default path runs for real, through make)" \
    "OK -- manifests/v1.0.0.sha256 reproduces byte-for-byte from v1.0.0" "$OUT54"

# ---------------------------------------------------------------------------
echo ""
echo "=== Section 5.5: THE MAKE-LEVEL EXPANSION CAVEAT (claude-workflow-"
echo "plugin-h2zz round 8, R8-F2, LOW) -- surviving the RECIPE unspliced"
echo "(Section 5 above) is not the same claim as surviving MAKE ITSELF"
echo "unexpanded; an earlier revision of 5.3b's own assertion name"
echo "conflated the two =="
# `git check-ref-format` has no objection to a tag containing make's OWN
# function-call syntax any more than it objects to shell metacharacters
# (Section 5's own header comment already established the shell-metachar
# case; this is the make-level analogue, and the reason this value matters
# at all -- an operator could genuinely tag a release "v$(id)" by accident).
CRF_MAKE_RC=0
# shellcheck disable=SC2016  # single-quoted on purpose: this is a LITERAL
# ref name being validated, never meant to expand.
git check-ref-format 'refs/tags/v$(id)' >/dev/null 2>&1 || CRF_MAKE_RC=$?
assert_eq "5.5.0 NON-VACUITY: v\$(id) is a LEGAL git ref (an operator-reachable value, not a synthetic string)" \
    "0" "$CRF_MAKE_RC"

# 5.5.1 precondition: the shipped Makefile carries the fix -- two top-level
# lines, anchored to TEXT (this file's own ASSERTION ANCHORING convention),
# immediately above the verify-release recipe.
# shellcheck disable=SC2016  # single-quoted on purpose: this is the LITERAL
# text of the anchor line being grepped/matched for below, not an expression
# to expand in THIS script's own shell.
OVERRIDE_LINE='override RELEASE_TAG := $(value RELEASE_TAG)'
EXPORT_LINE='export RELEASE_TAG'
assert_eq "5.5.1 precondition: the shipped Makefile carries the override line" \
    "yes" "$(grep -qF "$OVERRIDE_LINE" "$MAKEFILE" && echo yes || echo no)"
assert_eq "5.5.1b precondition: ...and the export line" \
    "yes" "$(grep -qF "$EXPORT_LINE" "$MAKEFILE" && echo yes || echo no)"

# 5.5.2 MUTANT -- a COPY of the shipped Makefile with JUST those two lines
# removed, same discipline as Section 5.1's line-exact reconstruction (a
# regex substitution is hostile to a Makefile's significant whitespace).
MUT_NOOVERRIDE="$WORK/Makefile.no-override"
MUT_NOOVERRIDE_HITS=0
: > "$MUT_NOOVERRIDE"
while IFS= read -r _s55_line || [ -n "$_s55_line" ]; do
    if [ "$_s55_line" = "$OVERRIDE_LINE" ] || [ "$_s55_line" = "$EXPORT_LINE" ]; then
        MUT_NOOVERRIDE_HITS=$((MUT_NOOVERRIDE_HITS + 1))
        continue
    fi
    printf '%s\n' "$_s55_line" >> "$MUT_NOOVERRIDE"
done < "$MAKEFILE"
assert_eq "5.5.2 NON-VACUITY: the mutant removed exactly the two fix lines, nothing else" \
    "2" "$MUT_NOOVERRIDE_HITS"
assert_eq "5.5.2b ...and the mutant is otherwise byte-identical to the shipped Makefile (a pure two-line deletion)" \
    "2" "$(diff "$MAKEFILE" "$MUT_NOOVERRIDE" 2>/dev/null | grep -c '^[<>]' | tr -d ' \n')"

# 5.5.3 SPECIFIC MISBEHAVIOUR CLOSED -- the mutant, executed for REAL against
# this project's own real tree (safe: verify-release-manifest.sh fails
# closed at the table-missing precondition, same as 5.2b/5.3c above, long
# before anything that reads or writes the repository). This is the exact
# reproduction the task's own diagnosis used, run here against a
# reconstructed pre-fix Makefile rather than asserted from memory.
# shellcheck disable=SC2016  # single-quoted on purpose: this is the LITERAL
# value the task's own diagnosis reproduced with, passed to `make` untouched
# by THIS script's shell -- expanding it here would defeat the whole point.
OUT55A=$(make -C "$PROJECT_DIR" -f "$MUT_NOOVERRIDE" verify-release 'RELEASE_TAG=v$(id)' 2>&1)
assert_contains "5.5.3 SPECIFIC MISBEHAVIOUR CLOSED: the PRE-FIX mutant collapses \$(id) to empty (R8-F2 reproduced)" \
    "manifests/v.sha256 has not been frozen yet" "$OUT55A"
# shellcheck disable=SC2016  # single-quoted on purpose: the needle is the
# LITERAL text we expect (and must NOT find) in the mutant's own output.
assert_eq "5.5.3b ...and never shows the whole value (the bug, not a coincidence)" \
    "no" "$(printf '%s' "$OUT55A" | grep -qF 'manifests/v$(id).sha256' && echo yes || echo no)"

# 5.5.4 THE FIX, BEHAVIOURAL -- the SAME value, against the SHIPPED Makefile
# (no mutant, no -n): the round-trip the task's brief required.
# shellcheck disable=SC2016  # single-quoted on purpose: same literal value
# as 5.5.3 above, passed to `make` untouched by THIS script's own shell.
OUT55B=$(make -C "$PROJECT_DIR" verify-release 'RELEASE_TAG=v$(id)' 2>&1)
RC55B=$?
assert_eq "5.5.4 THE FIX: the shipped Makefile exits 2 (precondition -- no such tag/table exists, which is correct; this is a round-trip proof, not a claim that this value is a usable tag)" \
    "2" "$RC55B"
assert_contains "5.5.4b ...and the diagnostic carries the value WHOLE: manifests/v\$(id).sha256, never collapsed to manifests/v.sha256" \
    "manifests/v\$(id).sha256 has not been frozen yet" "$OUT55B"

# 5.5.5 RESTORE CONTROL -- the mutant's OWN no-override default path is
# unaffected by removing the fix lines (they only matter when RELEASE_TAG is
# actually set to something containing make's own syntax), proving 5.5.3 is
# specific to the injected value and not the mutant construction itself
# being broken in general.
OUT55C=$(CLAUDE_PROJECT_DIR="$R1" make -C "$PROJECT_DIR" -f "$MUT_NOOVERRIDE" verify-release 2>&1)
RC55C=$?
assert_eq "5.5.5 RESTORE CONTROL: the mutant's own no-argument default path still exits 0 against a fixture" \
    "0" "$RC55C"
assert_contains "5.5.5b ...and still reports OK for the fixture's own tag" \
    "OK -- manifests/v1.0.0.sha256 reproduces byte-for-byte from v1.0.0" "$OUT55C"

# ---------------------------------------------------------------------------
echo ""
echo "=== Section 6: THE RELEASE-VERIFY CI WORKFLOW (claude-workflow-plugin-"
echo "h2zz round 11, R11-F2, MEDIUM) -- release-verify.yml is the ONLY"
echo "automatic, post-push enforcement of the claim this script carries, and"
echo "shipped with zero coverage of its own structure. Same injection class"
echo "as Section 5/5.5's Makefile recipe (R5-F5's YAML half, R6-F2's Makefile"
echo "half); the Makefile got 15 assertions including an executing mutant,"
echo "the YAML got none -- this section closes that asymmetry =="
#
# WHY THIS FILE, NOT runner-completeness.test.sh. That file's own WIRING
# section (8i, legs 8.24-8.29) asserts something adjacent but different:
# that .github/workflows/test.yml's l1-unit job invokes THIS test tier the
# way the Makefile's test-ci recipe claims it does (STRICT_SECTIONS, MCP
# deps) -- an internal-harness completeness question. release-verify.yml is
# not part of that harness at all; it is the second of the two PRODUCTION
# contexts this script's own header names (the first is Section 5/5.5's
# Makefile recipe), so its coverage belongs beside its sibling, in the file
# that already owns the release-lifecycle gate and the other half of this
# exact injection class -- one file to read for "is RELEASE_TAG handled
# safely everywhere it reaches this script", not two.
#
# NO NEW DEPENDENCY. Like every section above, this one uses only
# bash/grep/awk/diff/git/make -- "valid YAML" below is checked structurally
# (no tab indentation, both top-level keys present), never via a parser
# dependency this L1 tier does not otherwise carry. That is deliberate, not
# an oversight: a guarded-but-absent optional dependency prints a `note:`
# skip under this codebase's own convention (see design-conform.test.sh
# Section 14), and a `note:` skip is exactly what turns STRICT_SECTIONS=1
# red in CI (this task's own CAUSE 6 diagnosis, doc-only-classifier.test.sh /
# claude-workflow-plugin-hzv8) -- the fix for a CI-red task must not risk
# introducing an eighth cause of the same shape.
RV_WF="$PROJECT_DIR/.github/workflows/release-verify.yml"

assert_eq "6.0 precondition: release-verify.yml exists" \
    "yes" "$([ -f "$RV_WF" ] && echo yes || echo no)"

if [ -f "$RV_WF" ]; then

# extract_run_block <file> -- everything after the job's one `run:` line, the
# literal shell text GitHub hands to the runner's shell for this step.
# Reused below against the shipped file and both mutants so the SAME
# extraction logic drives every leg, mutated or not.
# shellcheck disable=SC2317  # invoked indirectly via command substitution below
extract_run_block() {
    awk '/^        run:/{c=1;next} c' "$1"
}

# --- 6.1-6.3: STRUCTURE (a dependency-free stand-in for "parses as valid
# YAML" -- see the header note above for why this is not a parser check) ---
assert_eq "6.1 STRUCTURE: no tab characters anywhere (YAML forbids tab indentation -- a real parse failure, not a style nit)" \
    "0" "$(grep -cF "$(printf '\t')" "$RV_WF" | tr -d ' ')"
assert_eq "6.2 STRUCTURE: top-level 'on:' trigger key present" \
    "yes" "$(grep -qx 'on:' "$RV_WF" && echo yes || echo no)"
assert_eq "6.3 STRUCTURE: top-level 'jobs:' key present" \
    "yes" "$(grep -qx 'jobs:' "$RV_WF" && echo yes || echo no)"

# --- 6.4-6.6: TRIGGER --------------------------------------------------------
assert_eq "6.4 TRIGGER: triggers on push:" \
    "yes" "$(grep -qx '  push:' "$RV_WF" && echo yes || echo no)"
assert_eq "6.5 TRIGGER: the push trigger is tags:, not branches: -- a release gate that also fired on ordinary branch pushes would run before the tag it is named for necessarily exists" \
    "yes" "$(grep -qx '    tags:' "$RV_WF" && echo yes || echo no)"
assert_eq "6.5b TRIGGER: ...and 'branches:' does not also appear anywhere (this workflow has exactly one trigger shape)" \
    "0" "$(grep -c 'branches:' "$RV_WF" | tr -d ' ')"
assert_eq "6.6 TRIGGER: the tag pattern is v*, matching this repo's real tag names (v3.5.0, v4.0.0, v4.1.0, v5.0.0)" \
    "yes" "$(grep -qF -- "- 'v*'" "$RV_WF" && echo yes || echo no)"

# --- 6.7-6.9: CHECKOUT -------------------------------------------------------
assert_eq "6.7 CHECKOUT: uses actions/checkout@v4" \
    "yes" "$(grep -qF 'uses: actions/checkout@v4' "$RV_WF" && echo yes || echo no)"
assert_eq "6.8 CHECKOUT: fetch-depth: 0 is set (full history + tags, not the tag-push event's default single-commit checkout)" \
    "yes" "$(grep -qF 'fetch-depth: 0' "$RV_WF" && echo yes || echo no)"
assert_eq "6.9 CHECKOUT: a comment explains WHY -- the tag OBJECT, not just the commit the tag-push event checks out by default (so a future tidy-up cannot drop it without reading why it is there)" \
    "yes" "$(grep -qF 'against the FULL tag object' "$RV_WF" && echo yes || echo no)"

# --- 6.10-6.13: RELEASE_TAG via env:, never interpolated into run: (R5-F5) --
assert_eq "6.10 ENV: RELEASE_TAG is bound via a step-level env: key" \
    "yes" "$(grep -qx '        env:' "$RV_WF" && echo yes || echo no)"
# shellcheck disable=SC2016  # single-quoted on purpose: this is the LITERAL
# env-binding text being grepped for below, never meant to expand in THIS
# script's own shell.
assert_eq "6.10b ENV: ...to \${{ github.ref_name }} specifically -- the only place in this file a GitHub expression may safely appear" \
    "yes" "$(grep -qF 'RELEASE_TAG: ${{ github.ref_name }}' "$RV_WF" && echo yes || echo no)"

RV_RUN_BLOCK=$(extract_run_block "$RV_WF")
assert_eq "6.11 WIRING: the run: block was located" \
    "yes" "$([ -n "$RV_RUN_BLOCK" ] && echo yes || echo no)"
# shellcheck disable=SC2016  # single-quoted on purpose: '${{' is the LITERAL
# needle being counted, never meant to expand in THIS script's own shell.
assert_eq "6.12 SECURITY (R5-F5): the run: block contains NO \${{ ... }} expression -- RELEASE_TAG reaches the shell ONLY as the quoted variable reference \$RELEASE_TAG, never as GitHub-templated raw text spliced into the script before the shell parses it" \
    "0" "$(printf '%s' "$RV_RUN_BLOCK" | grep -cF '${{' | tr -d ' ')"
# shellcheck disable=SC2016  # single-quoted on purpose: the needle is the
# LITERAL, unexpanded text `$RELEASE_TAG` is expected to appear as in the
# run: block, never an expression to expand in THIS script's own shell.
assert_contains "6.12b ...it reads the quoted shell variable instead" \
    '"$RELEASE_TAG"' "$RV_RUN_BLOCK"
assert_contains "6.13 INVOCATION: the job actually invokes verify-release-manifest.sh" \
    "bash .claude/scripts/verify-release-manifest.sh" "$RV_RUN_BLOCK"

# --- 6.14-6.16: EXECUTION -- .claude/tests/README.md's pairing requirement,
# leg 4: "at least one leg observes the shipped artifact running". 6.11-6.13
# above prove the WIRING by reading the text; this drives it. RV_RUN_BLOCK
# is taken VERBATIM from the shipped file (never retyped) and run with the
# same working directory GitHub Actions would use for this step (the
# checked-out repo root) plus this test's own CLAUDE_PROJECT_DIR override
# pointed at Section 1's real local-tag fixture (R1) -- the same override
# verify-release-manifest.sh's own header documents as its (c) offline-test
# contract.
assert_eq "6.14 EXECUTION precondition: the extracted run: block parses as valid shell" \
    "0" "$(printf '%s\n' "$RV_RUN_BLOCK" | bash -n 2>/dev/null; echo $?)"
RV_EXEC_OUT=$(cd "$PROJECT_DIR" && CLAUDE_PROJECT_DIR="$R1" RELEASE_TAG="v1.0.0" bash -c "$RV_RUN_BLOCK" 2>&1)
RV_EXEC_RC=$?
assert_eq "6.15 EXECUTION: the shipped run: block, driven verbatim with a real RELEASE_TAG, exits 0 against Section 1's own matching fixture" \
    "0" "$RV_EXEC_RC"
assert_contains "6.16 ...and reports the same OK line Section 1 established for this fixture (the shipped YAML text really runs the shipped script, not a stand-in for it)" \
    "OK -- manifests/v1.0.0.sha256 reproduces byte-for-byte from v1.0.0" "$RV_EXEC_OUT"

# ---------------------------------------------------------------------------
echo ""
echo "--- Section 6, MUTANT A: the expression inlined directly into run:,"
echo "reverting the R5-F5 fix -- proves 6.12 is sensitive, not vacuous ---"
# shellcheck disable=SC2016  # single-quoted on purpose: the LITERAL,
# exact-text line this mutant reads from the shipped file (this file's own
# ASSERTION ANCHORING convention), never an expression to expand here.
RV_LINE_RUN_SHIPPED='          bash .claude/scripts/verify-release-manifest.sh "$RELEASE_TAG"'
# shellcheck disable=SC2016  # single-quoted on purpose: same convention --
# the LITERAL replacement text this mutant writes, never expanded here.
RV_LINE_RUN_INLINED='          bash .claude/scripts/verify-release-manifest.sh "${{ github.ref_name }}"'
assert_eq "6.17 precondition: the shipped run: line reads exactly what this mutant targets" \
    "yes" "$(grep -qF "$RV_LINE_RUN_SHIPPED" "$RV_WF" && echo yes || echo no)"

MUT_RV_INLINE="$WORK/release-verify.inline-expr.yml"
MUT_RV_INLINE_HITS=0
: > "$MUT_RV_INLINE"
while IFS= read -r _s6a_line || [ -n "$_s6a_line" ]; do
    if [ "$_s6a_line" = "$RV_LINE_RUN_SHIPPED" ]; then
        printf '%s\n' "$RV_LINE_RUN_INLINED" >> "$MUT_RV_INLINE"
        MUT_RV_INLINE_HITS=$((MUT_RV_INLINE_HITS + 1))
    else
        printf '%s\n' "$_s6a_line" >> "$MUT_RV_INLINE"
    fi
done < "$RV_WF"
assert_eq "6.18 NON-VACUITY (mutant A): the inline-expression mutant replaced the run: line exactly once" \
    "1" "$MUT_RV_INLINE_HITS"
assert_eq "6.18b ...and is otherwise byte-identical to the shipped workflow (a one-line diff, not a reimplementation)" \
    "2" "$(diff "$RV_WF" "$MUT_RV_INLINE" 2>/dev/null | grep -c '^[<>]' | tr -d ' \n')"

MUT_RV_INLINE_RUN_BLOCK=$(extract_run_block "$MUT_RV_INLINE")
# shellcheck disable=SC2016  # single-quoted on purpose: same LITERAL needle
# as 6.12 above, re-run against the mutant to prove it flips.
assert_eq "6.19 SPECIFIC MISBEHAVIOUR CLOSED (mutant A), TEXTUAL: assertion 6.12 (0 occurrences of \${{ in the run: block) would FAIL against this workflow -- it now finds one" \
    "1" "$(printf '%s' "$MUT_RV_INLINE_RUN_BLOCK" | grep -cF '${{' | tr -d ' ')"

# 6.20.x SPECIFIC MISBEHAVIOUR, BEHAVIOURAL -- GitHub's expression templating
# is a TEXT SUBSTITUTION performed on the run: block BEFORE the shell ever
# parses it (this script's own header, and the R5-F5 evidence, both make
# this claim; this leg exercises it instead of merely asserting it). A real,
# `git check-ref-format`-legal ref name containing a bare redirection --
# `v$(>MARKER)`, no command word and no space, since a space anywhere makes
# a ref ILLEGAL and `touch MARKER` cannot be spelled without one -- spliced
# in place of the literal `${{ github.ref_name }}` token exactly the way
# GitHub's templating would splice it, then handed to bash: the same
# marker-file technique Section 5.2b uses for the Makefile twin.
RV_MUT_MARKER="$WORK/r11f2-mutant-a.marker"
rm -f "$RV_MUT_MARKER"
RV_INJECT_VALUE="v\$(>$RV_MUT_MARKER)"
CRF_REF_RC=0
git check-ref-format "refs/tags/$RV_INJECT_VALUE" >/dev/null 2>&1 || CRF_REF_RC=$?
assert_eq "6.20.0 NON-VACUITY: the exact injected ref value below is itself a LEGAL git ref (an attacker-reachable tag, not a synthetic string this workflow could never actually see)" \
    "0" "$CRF_REF_RC"
RV_TEMPLATED_CMD=$(printf '%s' "$MUT_RV_INLINE_RUN_BLOCK" | sed "s|\${{ github\.ref_name }}|$RV_INJECT_VALUE|")
RV_MUT_EXEC_OUT=$(cd "$PROJECT_DIR" && bash -c "$RV_TEMPLATED_CMD" 2>&1)
RV_MUT_EXEC_RC=$?
assert_eq "6.20 SPECIFIC MISBEHAVIOUR, BEHAVIOURAL (mutant A): GitHub's own post-templating text genuinely executes the injected redirection (marker file created)" \
    "yes" "$([ -f "$RV_MUT_MARKER" ] && echo yes || echo no)"
assert_contains "6.20b ...and the real script receives the CORRUPTED value too -- command substitution collapsed the ref to a bare 'v', not the attacker's literal text (the injected command runs AND the check that follows is confused about what it is even checking)" \
    "manifests/v.sha256 has not been frozen yet" "$RV_MUT_EXEC_OUT"
assert_eq "6.20c ...the real script's own exit code (2, precondition error) still propagates un-masked -- this injection corrupts the ARGUMENT rather than masking the exit code the way the Makefile twin's command-chaining does (Section 5.2d)" \
    "2" "$RV_MUT_EXEC_RC"

# 6.21.x RESTORE CONTROL -- the identical substitution attempt against the
# SHIPPED (unmutated) run: block, which contains no `${{ github.ref_name }}`
# token to replace at all (6.12 already proved zero occurrences): sed leaves
# it byte-identical, and running that untouched, real text creates no marker
# and still reports the genuine OK line against Section 1's own fixture.
RV_SHIPPED_TEMPLATED=$(printf '%s' "$RV_RUN_BLOCK" | sed "s|\${{ github\.ref_name }}|$RV_INJECT_VALUE|")
assert_eq "6.21 RESTORE CONTROL: the shipped run: block is byte-identical before and after the same substitution attempt (nothing to substitute)" \
    "yes" "$([ "$RV_SHIPPED_TEMPLATED" = "$RV_RUN_BLOCK" ] && echo yes || echo no)"
rm -f "$RV_MUT_MARKER"
RV_SHIPPED_TEMPLATED_OUT=$(cd "$PROJECT_DIR" && CLAUDE_PROJECT_DIR="$R1" RELEASE_TAG="v1.0.0" bash -c "$RV_SHIPPED_TEMPLATED" 2>&1)
assert_eq "6.21b ...and running it for real creates no marker (nothing injected actually runs)" \
    "no" "$([ -f "$RV_MUT_MARKER" ] && echo yes || echo no)"
assert_contains "6.21c ...the shipped path still reports the real OK line, unaffected by the substitution attempt" \
    "OK -- manifests/v1.0.0.sha256 reproduces byte-for-byte from v1.0.0" "$RV_SHIPPED_TEMPLATED_OUT"

# ---------------------------------------------------------------------------
echo ""
echo "--- Section 6, MUTANT B: fetch-depth: 0 dropped from the checkout step"
echo "-- the exact tidy-up this task's own diagnosis warns is a live risk"
echo "(this SAME change set removed it from the l1-unit job) ---"
RV_LINE_FETCHDEPTH='          fetch-depth: 0'
assert_eq "6.22 precondition: the shipped checkout step reads exactly what this mutant targets" \
    "yes" "$(grep -qF "$RV_LINE_FETCHDEPTH" "$RV_WF" && echo yes || echo no)"

MUT_RV_NODEPTH="$WORK/release-verify.no-fetch-depth.yml"
MUT_RV_NODEPTH_HITS=0
: > "$MUT_RV_NODEPTH"
while IFS= read -r _s6b_line || [ -n "$_s6b_line" ]; do
    if [ "$_s6b_line" = "$RV_LINE_FETCHDEPTH" ]; then
        MUT_RV_NODEPTH_HITS=$((MUT_RV_NODEPTH_HITS + 1))
        continue
    fi
    printf '%s\n' "$_s6b_line" >> "$MUT_RV_NODEPTH"
done < "$RV_WF"
assert_eq "6.23 NON-VACUITY (mutant B): the no-fetch-depth mutant removed exactly one line" \
    "1" "$MUT_RV_NODEPTH_HITS"
assert_eq "6.23b ...and is otherwise byte-identical to the shipped workflow (a pure one-line deletion)" \
    "1" "$(diff "$RV_WF" "$MUT_RV_NODEPTH" 2>/dev/null | grep -c '^[<>]' | tr -d ' \n')"
assert_eq "6.24 SPECIFIC MISBEHAVIOUR CLOSED (mutant B): assertion 6.8 (fetch-depth: 0 present) would FAIL against this workflow -- the line is gone" \
    "no" "$(grep -qF "$RV_LINE_FETCHDEPTH" "$MUT_RV_NODEPTH" && echo yes || echo no)"
assert_eq "6.25 RESTORE CONTROL: the shipped workflow still carries fetch-depth: 0 after mutant B was built (building a mutant in \$WORK never touches the real repo file)" \
    "yes" "$(grep -qF "$RV_LINE_FETCHDEPTH" "$RV_WF" && echo yes || echo no)"

# NOT ATTEMPTED, DELIBERATELY: an execution leg proving fetch-depth: 1 (the
# default) actually breaks `git archive <tag>` / `git rev-parse --verify
# <tag>^{commit}` for a TAG-triggered checkout specifically. That failure
# mode lives inside actions/checkout's own shallow-fetch behaviour for a
# `push: tags:` event, which cannot be honestly reproduced offline without a
# real GitHub-hosted runner -- asserting a specific breakage here would be a
# guess dressed as a measurement (this codebase's own evidence-before-fix
# discipline: say what you do not know rather than paper over the gap). The
# structural pair above (6.8/6.9 shipped, 6.22-6.25 mutant) is the full claim
# for this property; Section 6's EXECUTION leg (6.14-6.16) already discharges
# the pairing requirement's leg 4 for this whole section, so this is a scope
# decision, not a gap in it.

fi

echo ""
if [ "$FAIL" -eq 0 ]; then
    echo "PASSED: $PASS assertion(s)"
    exit 0
else
    echo "FAILED: $FAIL assertion(s) (of $((PASS + FAIL)))"
    printf '  - %s\n' "${FAILED_TESTS[@]}"
    exit 1
fi
